### ISSUE TITLE
de-client.py doesn't work with new decisionengine framework 0.3.4

### ISSUE THREAD

**Issue by paragmhashilkar** [HEPCloud/decisionengine#20]
upgraded decisionengine rpm from 0.3.3 to 0.3.4.  de-client.py code itself appears to be the same as what I was running before.  However we now get the following

```
[root@hepcsvc03 decisionengine]# de-client --status
Traceback (most recent call last):
  File "/usr/bin/de-client", line 75, in 
    print s.status()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in call
    return self.send(self.name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1591, in request
    verbose=self.verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])


xmlrpclib.Fault: :'module' object has no attribute '_state_names'">
```

**Comment by paragmhashilkar** [comment]
Fixed in #21
